"""移动端同步相关文案。"""

from __future__ import annotations

from typing import Any

_TEXTS = {
    "sync.status.offline": "未连接",
    "sync.status.disabled": "当前平台暂未开放账号同步",
    "sync.status.need_env": "请先填写授权码",
    "sync.status.need_config": "请先保存授权码",
    "sync.status.need_login": "请登录以同步数据",
    "sync.status.syncing": "同步中…",
    "sync.status.ok": "已同步 ✓",
    "sync.status.error": "同步失败：{msg}",
    "sync.login.ok": "登录成功，正在同步",
    "sync.retry": "重试同步",
    "sync.pause": "暂停自动同步",
    "sync.resume": "恢复自动同步",
    "sync.err.empty_env": "请输入授权码",
    "sync.err.empty": "请输入手机号和密码",
    "sync.err.empty_password": "请输入手机号和密码",
    "sync.err.bad_credentials": "手机号或密码错误",
    "sync.err.need_config": "未配置授权码，请在账号页填写并保存",
    "sync.err.empty_code": "请输入短信验证码",
    "sync.err.need_sms_first": "请先点击「获取验证码」",
    "sync.err.need_register_sms": "请先点击「获取验证码」（注册专用）",
    "sync.err.need_login_sms": "请使用登录验证码，或重新获取",
    "sync.err.bad_code": "验证码错误或已过期",
    "sync.err.already_registered": "该手机号已注册，请直接登录",
    "sync.err.user_not_found": "该手机号尚未注册，请先注册",
    "sync.err.windows_only": "账号同步目前仅支持 Windows 桌面版",
    "sync.sms.sent": "验证码已发送，请查收短信",
    "sync.env.changed_relogin": "授权码已更新，请重新登录",
    "assign.err.need_login": "请先登录后再派发任务",
    "assign.err.not_found": "未找到该手机号用户，请对方先登录一次",
    "assign.err.empty_recipient": "请输入对方手机号或昵称",
    "assign.err.contact_not_found": "未找到该昵称，请先在账号页添加联系人",
    "assign.err.duplicate_nickname": "昵称重复，请使用唯一昵称",
    "assign.err.empty_reject_reason": "请填写回退理由",
    "assign.err.empty_cancel_reason": "请填写撤回理由",
    "assign.err.not_finished": "该任务尚未结束，无法清除",
    "contacts.err.empty_nickname": "请输入昵称",
    "assign.err.self": "不能派发任务给自己",
    "assign.err.bad_phone": "手机号格式不正确",
    "assign.err.empty_title": "请输入任务标题",
    "assign.err.forbidden": "当前状态无法执行此操作",
    "assign.hint.inbox": "接受或拒绝他人派发的任务",
    "assign.hint.outbox": "填写对方手机号或昵称派发",
    "assign.description.placeholder": "任务说明（可选）",
    "assign.description.show": "说明：{text}",
    "assign.dispatch": "派发任务",
    "assign.dispatch.ok": "任务已派发",
    "assign.status.pending": "待处理",
    "assign.status.accepted": "已接受",
    "assign.status.rejected": "已回退",
    "assign.status.completed": "已完成",
    "assign.status.cancelled": "已撤回",
    "assign.dispatched_at": "派出于 {datetime}",
    "assign.completed_at": "完成于 {datetime}",
    "todo.created_at": "添加于 {datetime}",
    "todo.completed_at": "完成于 {datetime}",
    "sync.env.save": "保存授权码",
    "sync.env.saved": "授权码已保存",
    "assign.section.inbox_pending": "尚未接受",
    "assign.section.inbox_accepted": "已经接受",
    "assign.section.inbox_rejected": "已经回退",
    "assign.section.inbox_cancelled": "已撤回",
    "assign.section.outbox_pending": "对方尚未接收",
    "assign.section.outbox_accepted": "对方已接受",
    "assign.section.outbox_rejected": "对方退回",
    "assign.section.outbox_cancelled": "已撤回",
    "assign.clear_one": "清除",
    "todo.archive.hint": "已完成任务按日期归档，可还原或清除",
    "todo.archive.empty": "暂无已完成任务",
    "todo.archive.day_header": "{date} · {count} 项",
    "todo.archive.section.personal": "个人待办",
    "todo.archive.section.inbox": "派给我的（已完成）",
    "todo.archive.section.outbox": "我派出的（已完成）",
    "todo.archive.clear": "清除已归档",
    "todo.archive.clear.none": "没有可清除的已归档任务",
    "todo.archive.clear.summary": "已清除 {count} 条已归档任务",
    "todo.hint": "添加任务 · 完成或删除 · 归档查看历史",
    "todo.add": "添加",
    "prio.high": "高级",
    "prio.med": "中级",
    "prio.low": "低级",
    "todo.empty.personal": "暂无个人待办",
    "todo.empty.inbox": "暂无派给您的任务",
    "todo.empty.outbox": "暂无已派出的任务",
    "todo.tab.personal": "个人待办",
    "todo.tab.inbox": "派给我的",
    "todo.tab.outbox": "我派出的",
    "todo.tab.archive": "归档",
}


def tr(key: str, **kwargs: Any) -> str:
    text = _TEXTS.get(key, key)
    if kwargs:
        try:
            return text.format(**kwargs)
        except KeyError:
            return text
    return text
