"""MSI 安装向导 UI 表（无位图，适用于 msilib 回退方案）。"""

from __future__ import annotations

# 精简向导：欢迎 → 确认安装 → 进度 → 完成
# 由 build_msi.py 写入 Property 表
WIZARD_PROPERTIES = [
    ("ALLUSERS", "2"),
    # 强制 per-user，避免管理员账户下 ALLUSERS 被提升为 1 导致静默安装 1925
    ("MSIINSTALLPERUSER", "1"),
    ("ARPNOMODIFY", "1"),
    ("INSTALLLEVEL", "3"),
    ("InstallMode", "Typical"),
    ("Progress1", "Installing"),
    ("Progress2", "installs"),
    ("Setup", "Setup"),
    ("Wizard", "Setup Wizard"),
    ("ButtonText_Back", "< &Back"),
    ("ButtonText_Cancel", "Cancel"),
    ("ButtonText_Finish", "&Finish"),
    ("ButtonText_Install", "&Install"),
    ("ButtonText_Next", "&Next >"),
    ("ButtonText_No", "&No"),
    ("ButtonText_Yes", "&Yes"),
    ("DefaultUIFont", "DlgFont8"),
    ("DlgTitleFont", "{\\DlgFontBold8}"),
    ("ErrorDialog", "ErrorDlg"),
    ("INSTALLDESKTOPSHORTCUT", "1"),
    ("INSTALLSTARTUPSHORTCUT", "0"),
]

Dialog = [
    ("WelcomeDlg", 50, 50, 370, 270, 3, "[ProductName] Setup", "Next", "Next", "Cancel"),
    ("OptionsDlg", 50, 50, 370, 270, 3, "[ProductName] Setup", "Next", "Next", "Cancel"),
    ("VerifyReadyDlg", 50, 50, 370, 270, 35, "[ProductName] Setup", "Install", "Install", "Cancel"),
    ("PrepareDlg", 50, 50, 370, 270, 1, "[ProductName] Setup", "Cancel", "Cancel", "Cancel"),
    ("ProgressDlg", 50, 50, 370, 270, 1, "[ProductName] Setup", "Cancel", "Cancel", "Cancel"),
    ("ExitDialog", 50, 50, 370, 270, 3, "[ProductName] Setup", "Finish", "Finish", "Finish"),
    ("FatalError", 50, 50, 370, 270, 3, "[ProductName] Setup", "Finish", "Finish", "Finish"),
    ("UserExit", 50, 50, 370, 270, 3, "[ProductName] Setup", "Finish", "Finish", "Finish"),
    ("CancelDlg", 50, 10, 260, 85, 3, "[ProductName] Setup", "No", "No", "No"),
    # ICE20：错误对话框，Property ErrorDialog=ErrorDlg 依赖此表
    ("ErrorDlg", 50, 10, 330, 101, 65543, "[ProductName] Setup", "ErrorText", None, None),
]

Control = [
    ("WelcomeDlg", "Title", "Text", 20, 15, 330, 30, 196611, None,
     "{\\DlgFontBold8}Welcome to [ProductName]", None, None),
    ("WelcomeDlg", "Description", "Text", 20, 55, 330, 80, 196611, None,
     "This wizard will install [ProductName] on your computer. Click Next to continue or Cancel to exit.",
     None, None),
    ("WelcomeDlg", "BottomLine", "Line", 0, 234, 370, 0, 1, None, None, None, None),
    ("WelcomeDlg", "Back", "PushButton", 180, 243, 56, 17, 1, None, "[ButtonText_Back]", "Next", None),
    ("WelcomeDlg", "Next", "PushButton", 236, 243, 56, 17, 3, None, "[ButtonText_Next]", "Cancel", None),
    ("WelcomeDlg", "Cancel", "PushButton", 304, 243, 56, 17, 3, None, "[ButtonText_Cancel]", "Back", None),
    ("OptionsDlg", "Title", "Text", 20, 15, 330, 20, 196611, None,
     "[DlgTitleFont]安装选项", None, None),
    ("OptionsDlg", "Description", "Text", 20, 40, 330, 30, 196611, None,
     "请选择需要的附加选项，然后点击「下一步」继续。", None, None),
    ("OptionsDlg", "DesktopShortcutCheck", "CheckBox", 20, 85, 330, 18, 3,
     "INSTALLDESKTOPSHORTCUT", "创建桌面快捷方式", "StartupShortcutCheck", None),
    ("OptionsDlg", "StartupShortcutCheck", "CheckBox", 20, 110, 330, 18, 3,
     "INSTALLSTARTUPSHORTCUT", "开机自动启动", "Back", None),
    ("OptionsDlg", "BottomLine", "Line", 0, 234, 370, 0, 1, None, None, None, None),
    ("OptionsDlg", "Back", "PushButton", 180, 243, 56, 17, 3, None, "[ButtonText_Back]", "Cancel", None),
    ("OptionsDlg", "Next", "PushButton", 236, 243, 56, 17, 3, None, "[ButtonText_Next]", "DesktopShortcutCheck", None),
    ("OptionsDlg", "Cancel", "PushButton", 304, 243, 56, 17, 3, None, "[ButtonText_Cancel]", "Next", None),
    ("VerifyReadyDlg", "Title", "Text", 20, 15, 330, 20, 196611, None,
     "[DlgTitleFont]Ready to Install", None, None),
    ("VerifyReadyDlg", "Text", "Text", 20, 55, 330, 80, 3, None,
     "Click Install to begin. Click Back to review, or Cancel to exit the wizard.", None, None),
    ("VerifyReadyDlg", "BottomLine", "Line", 0, 234, 370, 0, 1, None, None, None, None),
    ("VerifyReadyDlg", "Back", "PushButton", 180, 243, 56, 17, 3, None, "[ButtonText_Back]", "Install", None),
    ("VerifyReadyDlg", "Install", "PushButton", 236, 243, 56, 17, 3, None, "[ButtonText_Install]", "Cancel", None),
    ("VerifyReadyDlg", "Cancel", "PushButton", 304, 243, 56, 17, 3, None, "[ButtonText_Cancel]", "Back", None),
    ("PrepareDlg", "Title", "Text", 20, 15, 330, 30, 196611, None,
     "{\\DlgFontBold8}Welcome to [ProductName]", None, None),
    ("PrepareDlg", "Description", "Text", 20, 55, 330, 40, 196611, None,
     "Please wait while Setup prepares the wizard.", None, None),
    ("PrepareDlg", "ActionText", "Text", 20, 110, 330, 20, 196611, None, None, None, None),
    ("PrepareDlg", "ActionData", "Text", 20, 135, 330, 30, 196611, None, None, None, None),
    ("PrepareDlg", "BottomLine", "Line", 0, 234, 370, 0, 1, None, None, None, None),
    ("PrepareDlg", "Cancel", "PushButton", 304, 243, 56, 17, 3, None, "[ButtonText_Cancel]", "Cancel", None),
    ("ProgressDlg", "Title", "Text", 20, 15, 330, 20, 196611, None,
     "[DlgTitleFont][Progress1] [ProductName]", None, None),
    ("ProgressDlg", "Text", "Text", 20, 45, 330, 30, 3, None,
     "Please wait while Setup [Progress2] [ProductName].", None, None),
    ("ProgressDlg", "StatusLabel", "Text", 35, 100, 35, 10, 3, None, "Status:", None, None),
    ("ProgressDlg", "ActionText", "Text", 70, 100, 265, 10, 3, None, None, None, None),
    ("ProgressDlg", "ProgressBar", "ProgressBar", 35, 115, 300, 10, 65537, None, "Progress done", None, None),
    ("ProgressDlg", "BottomLine", "Line", 0, 234, 370, 0, 1, None, None, None, None),
    ("ProgressDlg", "Cancel", "PushButton", 304, 243, 56, 17, 3, None, "[ButtonText_Cancel]", "Cancel", None),
    ("ExitDialog", "Title", "Text", 20, 15, 330, 30, 196611, None,
     "{\\DlgFontBold8}Completing [ProductName] Setup", None, None),
    ("ExitDialog", "Description", "Text", 20, 55, 330, 40, 196611, None,
     "Click Finish to exit the wizard.", None, None),
    ("ExitDialog", "BottomLine", "Line", 0, 234, 370, 0, 1, None, None, None, None),
    ("ExitDialog", "Finish", "PushButton", 236, 243, 56, 17, 3, None, "[ButtonText_Finish]", "Finish", None),
    ("FatalError", "Title", "Text", 20, 15, 330, 30, 196611, None,
     "{\\DlgFontBold8}Setup ended prematurely", None, None),
    ("FatalError", "Description1", "Text", 20, 55, 330, 60, 196611, None,
     "An error occurred. Your system has not been modified.", None, None),
    ("FatalError", "Finish", "PushButton", 236, 243, 56, 17, 3, None, "[ButtonText_Finish]", "Finish", None),
    ("UserExit", "Title", "Text", 20, 15, 330, 30, 196611, None,
     "{\\DlgFontBold8}Setup was interrupted", None, None),
    ("UserExit", "Description1", "Text", 20, 55, 330, 60, 196611, None,
     "Setup was cancelled. Your system has not been modified.", None, None),
    ("UserExit", "Finish", "PushButton", 236, 243, 56, 17, 3, None, "[ButtonText_Finish]", "Finish", None),
    ("CancelDlg", "Text", "Text", 48, 15, 194, 30, 3, None,
     "Are you sure you want to cancel [ProductName] installation?", None, None),
    ("CancelDlg", "Yes", "PushButton", 72, 57, 56, 17, 3, None, "[ButtonText_Yes]", "No", None),
    ("CancelDlg", "No", "PushButton", 132, 57, 56, 17, 3, None, "[ButtonText_No]", "Yes", None),
    ("ErrorDlg", "ErrorIcon", "Icon", 15, 9, 24, 24, 5242881, None, "WalleIcon", None, None),
    ("ErrorDlg", "ErrorText", "Text", 50, 9, 280, 48, 3, None, "", None, None),
    ("ErrorDlg", "N", "PushButton", 120, 72, 81, 21, 3, None, "No", None, None),
    ("ErrorDlg", "Y", "PushButton", 240, 72, 81, 21, 3, None, "Yes", None, None),
    ("ErrorDlg", "A", "PushButton", 0, 72, 81, 21, 3, None, "Abort", None, None),
    ("ErrorDlg", "C", "PushButton", 42, 72, 81, 21, 3, None, "Cancel", None, None),
    ("ErrorDlg", "I", "PushButton", 81, 72, 81, 21, 3, None, "Ignore", None, None),
    ("ErrorDlg", "O", "PushButton", 159, 72, 81, 21, 3, None, "Ok", None, None),
    ("ErrorDlg", "R", "PushButton", 198, 72, 81, 21, 3, None, "Retry", None, None),
]

CheckBox = [
    ("INSTALLDESKTOPSHORTCUT", "1"),
    ("INSTALLSTARTUPSHORTCUT", "1"),
]

ControlEvent = [
    ("WelcomeDlg", "Cancel", "SpawnDialog", "CancelDlg", "1", None),
    ("WelcomeDlg", "Next", "NewDialog", "OptionsDlg", "1", None),
    ("OptionsDlg", "Cancel", "SpawnDialog", "CancelDlg", "1", None),
    ("OptionsDlg", "Back", "NewDialog", "WelcomeDlg", "1", None),
    ("OptionsDlg", "Next", "NewDialog", "VerifyReadyDlg", "1", None),
    ("VerifyReadyDlg", "Cancel", "SpawnDialog", "CancelDlg", "1", None),
    ("VerifyReadyDlg", "Back", "NewDialog", "OptionsDlg", "1", None),
    ("VerifyReadyDlg", "Install", "EndDialog", "Return", "1", None),
    ("PrepareDlg", "Cancel", "SpawnDialog", "CancelDlg", "1", None),
    ("ProgressDlg", "Cancel", "SpawnDialog", "CancelDlg", "1", None),
    ("CancelDlg", "No", "EndDialog", "Return", "1", None),
    ("CancelDlg", "Yes", "EndDialog", "Exit", "1", None),
    ("ExitDialog", "Finish", "EndDialog", "Return", "1", None),
    ("FatalError", "Finish", "EndDialog", "Exit", "1", None),
    ("UserExit", "Finish", "EndDialog", "Exit", "1", None),
    ("ErrorDlg", "N", "EndDialog", "ErrorNo", "1", None),
    ("ErrorDlg", "Y", "EndDialog", "ErrorYes", "1", None),
    ("ErrorDlg", "A", "EndDialog", "ErrorAbort", "1", None),
    ("ErrorDlg", "C", "EndDialog", "ErrorCancel", "1", None),
    ("ErrorDlg", "I", "EndDialog", "ErrorIgnore", "1", None),
    ("ErrorDlg", "O", "EndDialog", "ErrorOk", "1", None),
    ("ErrorDlg", "R", "EndDialog", "ErrorRetry", "1", None),
]

EventMapping = [
    ("PrepareDlg", "ActionData", "ActionData", "Text"),
    ("PrepareDlg", "ActionText", "ActionText", "Text"),
    ("ProgressDlg", "ActionText", "ActionText", "Text"),
    ("ProgressDlg", "ProgressBar", "SetProgress", "Progress"),
]

TextStyle = [
    ("DlgFont8", "Tahoma", 9, None, 0),
    ("DlgFontBold8", "Tahoma", 9, None, 1),
]

InstallUISequence = [
    ("FindRelatedProducts", None, 200),
    ("PrepareDlg", None, 140),
    ("WelcomeDlg", "NOT Installed", 1230),
    ("OptionsDlg", "NOT Installed", 1235),
    ("VerifyReadyDlg", "NOT Installed", 1240),
    ("ProgressDlg", None, 1280),
    ("ExecuteAction", None, 1300),
    ("ExitDialog", None, -1),
    ("FatalError", None, -3),
    ("UserExit", None, -2),
    ("AppSearch", None, 400),
    ("LaunchConditions", None, 100),
    ("ValidateProductID", None, 700),
    ("CostInitialize", None, 800),
    ("FileCost", None, 900),
    ("CostFinalize", None, 1000),
]

UI_TABLES = [
    "Dialog",
    "Control",
    "CheckBox",
    "ControlEvent",
    "EventMapping",
    "TextStyle",
]
